CREATE TABLE Admin(
    ADMIN_ID int NOT NULL AUTO_INCREMENT,
    ADMIN_LOGIN varchar(255) NOT NULL,
    ADMIN_PASSWORD varchar(255) NOT NULL,

    PRIMARY KEY (ADMIN_ID)
);

CREATE TABLE Test_Person(
    TEST_PERSON_ID int NOT NULL AUTO_INCREMENT,
    TEST_PERSON_NAME varchar(255) NOT NULL,
    TEST_PERSON_SURNAME varchar(255) NOT NULL,
    TEST_PERSON_MAIL varchar(255) NOT NULL,

    PRIMARY KEY (TEST_PERSON_ID)
);

CREATE TABLE Statistic(
    STATISTIC_ID int NOT NULL AUTO_INCREMENT,
    TEST_PERSON_ID int NOT NULL,
    TOPIC_ID int NOT NULL,
    STATISTIC_PERSON varchar(255) NOT NULL,

    PRIMARY KEY (STATISTIC_ID)
);



INSERT INTO Admin VALUES('1','login1','pass1');
INSERT INTO Admin VALUES('2','login2','pass2');
INSERT INTO Admin VALUES('3','login3','pass3');
INSERT INTO Admin VALUES('4','login4','pass4');


